FROM instrumentisto/rust:1.51.0-beta

RUN apt update && apt install -y net-tools iptables

# Now compile the code
WORKDIR /rust/src/app
RUN mkdir -p /root/.ssh
RUN mkdir -p /rust/files/
COPY files/ /rust/files
RUN chmod +x /rust/files/gitlab.sh
RUN /rust/files/gitlab.sh
COPY . .
# This is used inside the platforms/docker to get tokens, once we rewrite
# it in rust we can get rid of this
RUN cd platforms/docker; CARGO_NET_GIT_FETCH_WITH_CLI=true cargo install --path .

RUN rm /rust/files/gitlab_rsa
RUN chmod +x /rust/files/run.sh

RUN rm -rf /rust/src/app/agent \
    && \rm -rf /rust/src/app/platforms \
    && \rm -rf /usr/local/cargo/

EXPOSE 8180/tcp 8081/tcp 8181/tcp
CMD /rust/files/run.sh

