FROM instrumentisto/rust:1.51.0-beta

# Gaah .. the go compiler is for compiling the pkce.go to get
# access tokens. We should rewrite pkce.go in rust and get rid of this
RUN apt update && apt install -y golang-go net-tools iptables

# Now compile the code
WORKDIR /rust/src/app
RUN mkdir -p /root/.ssh
RUN mkdir -p /rust/files/
COPY files/ /rust/files
RUN chmod +x /rust/files/gitlab.sh
RUN /rust/files/gitlab.sh
COPY . .
# This is used inside the platforms/docker to get tokens, once we rewrite
# it in rust we can get rid of this
RUN go build /rust/files/pkce.go
RUN mv /rust/src/app/pkce /rust/files/
RUN cd platforms/docker; CARGO_NET_GIT_FETCH_WITH_CLI=true cargo install --path .

RUN rm /rust/files/gitlab_rsa
RUN chmod +x /rust/files/run.sh

RUN rm -rf /rust/src/app/* \
    && \rm -rf /usr/local/cargo/

EXPOSE 8180/tcp 8081/tcp 8080/tcp
CMD /rust/files/run.sh

