FROM golang:1.15.7-alpine3.12
RUN apk update && apk add lighttpd && apk add git && apk add openssh

# For emulating a private URL webservice
RUN mkdir /etc/lighttpd/certs
COPY files/http/certs/* /etc/lighttpd/certs/
RUN chmod 400 /etc/lighttpd/certs/lighttpd.pem
COPY files/http/config/lighttpd.conf /etc/lighttpd/lighttpd.conf
RUN chmod 777 /var/log/lighttpd

# Now compile the code
WORKDIR /go/src/app
RUN mkdir -p /root/.ssh
RUN mkdir -p /go/files/
COPY files/ /go/files
RUN chmod +x /go/files/gitlab.sh
RUN /go/files/gitlab.sh
RUN go env -w GOPRIVATE="gitlab.com"
RUN go env -w GO111MODULE="on"
COPY . .
RUN go get -d -v ./... 
RUN cd connector; go install -v ./...
RUN rm -r -f /go/src/app/* \
    && \rm -r -f /go/pkg/mod \
    && \rm -r -f /go/pkg/sumdb

RUN rm /go/files/gitlab_rsa

RUN apk del git && apk del openssh

RUN chmod +x /go/files/run.sh
EXPOSE 8180/tcp 8081/tcp 8181/tcp
CMD /go/files/run.sh
