[package]
name = "nextensio"
version = "0.1.0"
authors = ["Nextensio <team@nextensio.net>"]
edition = "2018"

[dependencies]
log = "0.4.14"
env_logger = "0.8.3"
libc = "0.2.86"
serde = "1.0.124"
serde_json = "1.0.64"
regex = "1"
oauth2 = "3.0"
rpassword = "5.0"
signal-hook = "0.3.9"
reqwest = { version = "0.9.24", features = ["tls"]}
uuid = { version = "0.8", features = ["v4"] }
clap = "2.33.3"
agent = { path = "../../agent" }
